"use server";

import { Webhook } from "standardwebhooks";
import resetLinkEmail from "@/utils/email-templates/reset-password";
import { Resend } from "resend";

const SEND_EMAIL_HOOK_SECRET = process.env.SEND_EMAIL_HOOK_SECRET.replace(
  "v1,whsec_",
  ""
);

/**************************************************************************
 *
 * This is a POST API endpoint used for receiving OTP tokens from Supabase
 * in order to send a custom email to the user with a password reset OTP code.
 *
 * This works in conjunction with Supabase Auth Hooks which sends the password
 * reset information to this endpoint instead of sending it's own emails to
 * the user.
 *
 **************************************************************************/

export async function POST(request) {
  const wh = new Webhook(SEND_EMAIL_HOOK_SECRET);

  const headers = Object.fromEntries(request.headers);
  const payload = await request.text();

  const responseHeaders = new Headers();
  responseHeaders.set("Content-Type", "application/json");

  try {
    //First verify that the webhook was actually generated by Supabase
    const { user, email_data } = wh.verify(payload, headers);

    const type = email_data.email_action_type;

    //If the email action type is "recovery", then you can send the token in a custom email
    // to the user

    if (type.toLowerCase() === "recovery") {
      const email = user.email;
      const token = email_data.token;
      const resend = new Resend(process.env.RESEND_API_KEY);

      const { data: emailData, error: emailError } = await resend.emails.send({
        from: `STM Golf Event <${process.env.SEND_FROM_EMAIL}>`,
        to: [email],
        subject: "STM Golf Dashboard: Reset Password",
        react: resetLinkEmail(token),
      });

      if (emailError && Object.keys(emailError).length >= 1) {
        throw new Error(emailError.message);
      }

      return new Response(JSON.stringify({}), {
        status: 200,
        headers: responseHeaders,
      });
    } else {
      throw new Error("Invalid OTP Type");
    }
  } catch (error) {
    return new Response(JSON.stringify({}), {
      status: 500,
      headers: responseHeaders,
    });
  }
}
