import { text, table } from "@pdfme/schemas";

export const template = {
  schemas: [
    [
      {
        name: "ReportTitle",
        type: "text",
        content: "Attendees Check In Form",
        position: { x: 41.63, y: 20.26 },
        width: 126.74,
        height: 12.44,
        rotate: 0,
        alignment: "center",
        verticalAlignment: "top",
        fontSize: 26,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: "#000000",
        fontName: "Roboto",
        backgroundColor: "",
        opacity: 1,
        strikethrough: false,
        underline: false,
        required: false,
        readOnly: true,
      },
      {
        name: "attendeesTable",
        type: "table",
        position: { x: 17.16, y: 41.83 },
        width: 175.68,
        height: 29.172800000000002,
        content: '[["",""]]',
        showHead: true,
        head: ["Name", "Hole"],
        headWidthPercentages: [63.62814415574751, 36.37185584425248],
        tableStyles: { borderWidth: 0.3, borderColor: "#000000" },
        headStyles: {
          fontName: "Roboto",
          fontSize: 13,
          characterSpacing: 0,
          alignment: "left",
          verticalAlignment: "middle",
          lineHeight: 1,
          fontColor: "#ffffff",
          borderColor: "",
          backgroundColor: "#000000",
          borderWidth: { top: 0, right: 0, bottom: 0, left: 0 },
          padding: { top: 5, right: 5, bottom: 5, left: 5 },
        },
        bodyStyles: {
          fontName: "Roboto",
          fontSize: 12,
          characterSpacing: 0,
          alignment: "left",
          verticalAlignment: "middle",
          lineHeight: 1,
          fontColor: "#000000",
          borderColor: "#888888",
          backgroundColor: "",
          alternateBackgroundColor: "#f5f5f5",
          borderWidth: {
            top: 0.1,
            right: 0.1,
            bottom: 0.1,
            left: 0.1,
          },
          padding: { top: 2, right: 2, bottom: 2, left: 2 },
        },
        columnStyles: {},
        required: false,
        readOnly: false,
      },
    ],
  ],
  basePdf: { width: 210, height: 297, padding: [20, 10, 20, 10] },
  pdfmeVersion: "5.4.1",
};

export const plugins = { text, table };
